//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_for_seminar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminstrator
    {
        public int AdmnID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
